# Generated by Django 3.1.5 on 2021-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_auto_20210129_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
